<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>false</InvariantGlobalization>
		<UserSecretsId>76496457-6cc6-42c0-9967-ebe1cf2367bb</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<EnableSourceLink>true</EnableSourceLink>
		<ServerGarbageCollection>true</ServerGarbageCollection>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Application\RoomAccessControl\**" />
		<Compile Remove="Domain\**" />
		<Content Remove="Application\RoomAccessControl\**" />
		<Content Remove="Domain\**" />
		<EmbeddedResource Remove="Application\RoomAccessControl\**" />
		<EmbeddedResource Remove="Domain\**" />
		<None Remove="Application\RoomAccessControl\**" />
		<None Remove="Domain\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Ardalis.Result.AspNetCore" Version="10.1.0" />
		<PackageReference Include="Ardalis.Result.FluentValidation" Version="10.1.0" />
		<PackageReference Include="AspNet.Security.OAuth.Vkontakte" Version="9.4.0" />
		<PackageReference Include="AspNetCore.Identity.Mongo" Version="10.1.0" />
		<PackageReference Include="gstreamer-sharp-netcore" Version="0.0.8" />
		<PackageReference Include="MediatR" Version="12.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="9.0.4" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.2" />
		<PackageReference Include="MimeTypesMap" Version="1.0.8" />
		<PackageReference Include="Mongo2Go" Version="4.1.0" />
		<PackageReference Include="MongoDB.Analyzer" Version="2.0.0" />
		<PackageReference Include="MongoDB.Driver" Version="3.4.0" />
		<PackageReference Include="MongoDB.Driver.Core.Extensions.DiagnosticSources" Version="2.1.0" />
		<PackageReference Include="OpenTelemetry" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.9.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="0.5.0-beta.6" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.9.0" />
		<PackageReference Include="Scrutor" Version="4.2.2" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="Serilog.Enrichers.Sensitive" Version="1.7.3" />
		<PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.0.0" />
		<PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="8.3.0" />
		<PackageReference Include="SonarAnalyzer.CSharp" Version="9.32.0.97167">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
		<PackageReference Include="System.Text.Json" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ContentRating.Domain\ContentRating.Domain.csproj" />
		<ProjectReference Include="..\ContentRating.Web.Contracts\ContentRating.Web.Contracts.csproj" />
	</ItemGroup>

</Project>
